EXTENSIONS = {
    '.mp3': 'Audio',
    '.wav': 'Audio',
    '.m4a': 'Audio',
    '.wma': 'Audio',

    '.docx': 'Documents', 
    '.xlsx': 'Documents',
    '.xla': 'Documents',
    '.xls': 'Documents',
    '.xlam': 'Documents',
    '.doc': 'Documents', 
    '.pdf': 'Documents', 
    '.csv': 'Documents', 
    '.excel': 'Documents',
    '.ics': 'Documents',
    '.txt': 'Documents',
    '.sql': 'Documents',
    '.pps': 'Documents',
    '.ppt': 'Documents',
    '.pptm': 'Documents',
    '.rtf': 'Documents',
    '.sldx': 'Documents',
    
    '.jpg': 'Images',
    '.png': 'Images',
    '.gif': 'Images',
    '.webp': 'Images',
    '.tif': 'Images',
    '.tiff': 'Images',
    '.psd': 'Images',
    '.raw': 'Images',
    '.bmp': 'Images',
    '.heif': 'Images',
    '.indd': 'Images',
    '.jpeg': 'Images',
    '.svg': 'Images',
    '.ai': 'Images',
    '.eps': 'Images',
    '.jif': 'Images',
    '.jpe': 'Images',
    
    '.zip': 'Other',
    '.7z': 'Other',
    '.php': 'Other',
    '.html': 'Other',
    '.deb': 'Other',
    '.ini': 'Other',
    '.rar': 'Other',
    '.tmp': 'Other',
    
    '.exe': 'Apps',
    '.msi': 'Apps',
    '.iso': 'Apps',

    '.mp4': 'Videos',
    '.ogg': 'Videos',
    '.avi': 'Videos',
    '.webm': 'Videos',
    '.mov': 'Videos',
    '.flv': 'Videos',
    '.mpeg': 'Videos',
    '.vob': 'Videos',
}

STORAGE_DIRS = ['Apps', 'Audio', 'Documents', 'Images', 'Videos', 'Other']